### PR TITLE
fixed unzipping of big files (was passing the wrong path)

### PR DESCRIPTION
**Pull request by tati-micheletti**

### CODE REVIEW

**Comment by achubaty** [comment]
is this related to #81?

**Comment by tati-micheletti** [comment]
Nope. This is actually a bug when using system call of unzip. It was not getting the path properly.

**Comment by eliotmcintire** [comment]
Only fail is on Travis, installing igraph. Unrelated to this PR

**Comment by tati-micheletti** [comment]
More specifically: only fails on AppVeyor due to igraph install problems...

**Pull request merged**
