### PR TITLE
revdep checks with GitHub Actions

### PR DESCRIPTION
**Pull request by achubaty**
**NOTE:** many of these packages are failing with the CRAN version already, so are not registering as 'new' failures.

should this workflow be 'non-blocking', or should we strive to ensure development versions of all our packages (not just the CRAN ones) are still working with latest `reproducible` changes?

### CODE REVIEW

**Comment by eliotmcintire** [comment]
We can only deal with CRAN packages. Any other packages should be non blocking. `reproducible` is being kicked off CRAN in 6 days if we don't push this version in the dayCRAN opens.

**Comment by achubaty** [comment]
this is currently non blocking - you can see the errors in actions logs, and for now, will require manual inspection.

**Comment by eliotmcintire** [comment]
It is not clear to me what this PR is doing. Can you please describe what the objective is? I also don't understand the 

> NOTE: many of these packages are failing with the CRAN version already, so are not registering as 'new' failures.

means. Many of _which_ packages are failing?

**Comment by achubaty** [comment]
This PR adds GitHub Action workflow to run reverse dependency checks so we can see downstream breakages more easily. Since this is detecting 'new' failures, existing failures in revdeps won't necessarily show up here right away, but the goal is to at first identify where downstream breakages can/do occur and then fix these problems.

**Comment by achubaty** [comment]
#354 is a prime example why we need to continuously run revdep checks. changing the return value of an exported function is likely to cause downstream breakages.

**Comment by eliotmcintire** [comment]
I think what this is doing is running reverse depends on the `development` branch of downstream packages. This would help identify these issues sooner so the package maintainers of those packages can adjust.

**Review by eliotmcintire — COMMENTED** [review]
I don't have the expertise to evaluate this yaml document

**Comment by eliotmcintire** [comment]
Are you able to deal with this? @achubaty

**Comment by achubaty** [comment]
I can merge this, but I've been waiting approval.

**Pull request merged**
