### PR TITLE
allow `SpatVector` in `studyAreaName`

### PR DESCRIPTION
**Pull request by CeresBarros**

### CODE REVIEW

**Comment by achubaty** [comment]
@CeresBarros please correct the error on R-devel:

```r
* checking tests ...
  Running 'test-all.R' [1[82](https://github.com/PredictiveEcology/reproducible/runs/7732184980?check_suite_focus=true#step:13:83)s]
 ERROR
Running the tests in 'tests/test-all.R' failed.
Last 13 lines of output:
   11. reproducible::preProcess(...)
   12. reproducible::downloadFile(...)
   18. reproducible:::downloadRemote(...)
   20. raster (local) `<fn>`(name = "GADM", country = "LUX", level = 0, path = "C:/Users/runneradmin/AppData/Local/Temp/RtmpMLl132/working_dir/RtmpM5QrFF/Require/NTXFEr")
  
  ══ Failed tests ════════════════════════════════════════════════════════════════
  ── Failure (test-cache.R:164:3): test file-backed raster caching ───────────────
  b1[1] > b2[1] is not TRUE
  
  `actual`:   FALSE
  `expected`: TRUE 
  
  [ FAIL 1 | WARN 2 | SKIP 21 | PASS 529 ]
  Error: Test failures
  Execution halted
```

**Comment by achubaty** [comment]
You may need to account for #256 here.

**Comment by CeresBarros** [comment]
I'll try to get to this ASAP, but likely not today

**Comment by CeresBarros** [comment]
@achubaty, sorry for the delay in getting to this. I've added wrapping for SpatVector before digesting the study area now.

**Comment by CeresBarros** [comment]
I think this could be merged now?

**Comment by CeresBarros** [comment]
@eliotmcintire can I close this?

**Comment by CeresBarros** [comment]
fixed in b9538e456043895c2d5a27d5960a6b923ba26b5b

**Pull request closed without merging**
